<?php
	
	/*
	 *****
	 *****    WPVR CONFIG FILE
	 *****
	 *****    THIS CONFIG FILE IS INTENDED TO ADVANCED USERS
	 *****    IF YOU ARE NOT, PLEASE DO NOT EDIT THIS FILE !
	 *****
	 *****
	 *
	 */
	
	
	/* USER DEFINED FUNCTIONS */
	
	/* Enable debug Mode */
	define( 'WPVR_DEBUG_MODE', false );
	
	/* Enable API debug Mode */
	define( 'WPVR_API_DEBUG_MODE', false );
	
	/* Enable API RESPONSE debugging */
	define( 'WPVR_API_RESPONSE_DEBUG', false);
	define( 'WPVR_ENABLE_ASYNC_DEBUG', false);
	
	/* Enable API debug Mode */
	define( 'WPVR_META_DEBUG_MODE', false );
	
	/* Enable ASYNC SOURCES RUN */
	//@Deprecated - @
	define( 'WPVR_ENABLE_ASYNC_RUN', true );
	define( 'WPVR_ENABLE_ASYNC_FETCH', true );
	/****************/
	
	define( 'WPVR_ASYNC_ADDING_BUFFER', 3 );
	
	/* Enable Image Correction */
	define( 'WPVR_ENABLE_THUMB_CORRECTION', false );
	
	/* Set this to true to automatically replace HD video thumbs by smaller ones to load pages faster. */
	define( 'WPVR_ENABLE_THUMB_DEFAULT_SIZES', false );
	
	/* Useful for external thumbnails to remove the black bars*/
	define( 'WPVR_FORCE_EXTERNAL_THUMB_HARD_CROP', false );
	
	/* Define your own cron Endpoint */
	define( 'WPVR_CRON_ENDPOINT', 'automation' );
	
	
	/* Enable Sandbox for testing purposes */
	define( 'WPVR_ENABLE_SANDBOX', false);
	
	/* Enable this if you have locked yourself out by mistake */
	define( 'WPVR_IS_LOCKED_OUT', false );
	
	/* Refuse sources with wanted videos bigger than this value ? */
	/* Set to FALSE to accept any number */
	define( 'WPVR_MAX_WANTED_VIDEOS', false );
	
	/* Automatically add video title words as tags ? */
	define( 'WPVR_TAGS_FROM_TITLE_ENABLE', false );
	
	/* Should the plugin accept empty source names ? */
	define( 'WPVR_ACCEPT_EMPTY_SOURCE_NAMES', false );
	
	/* Maximum number of Categories to autopost to  */
	define( 'WPVR_MAX_POSTING_CATS', 255 );
	
	/* Slug for uncategorized Category*/
	define( 'WPVR_UNCATEGORIZED', 'uncategorized' );
	
	
	/* Manage Videos Default Layout */
	/* Possible values : sgrid , bgrid , grid , list */
	define( 'WPVR_MANAGE_LAYOUT', 'bgrid' );
	
	/* Manage Videos Default Videos Per Page */
	define( 'WPVR_MANAGE_PERPAGE', 20 );
	define( 'WPVR_DEFERRED_PERPAGE', 40 );
	define( 'WPVR_UNWANTED_PERPAGE', 40 );
	
	/* Hard REfresh the AntiDuplicates Table on each Test and on each Run ? */
	/* Needs more resources */
	define( 'WPVR_ENABLE_HARD_REFRESH', false );
	
	/* SET THIS TO TRUE TO USE VIDEO SERVICES IMAGES WITHOUT DONWLOADING THUMBS */
	//@Deprecated
	define( 'WPVR_DISABLE_THUMBS_DOWNLOAD', true);
	
	
	/* USER DEFINED FUNCTIONS */
	/*************************************************/
	/* VIDEO SERVICES */
	define( 'WPVR_ENABLE_YOUTUBE', true );
	define( 'WPVR_ENABLE_DAILYMOTION', true );
	define( 'WPVR_ENABLE_VIMEO', true );
	/* VIDEO SERVICES  */
	
	
	/* COMPONENTS */
	
	/* Enable/Disable the plugin Addons */
	define( 'WPVR_ENABLE_ADDONS', true );
	
	/* Enable/Disable Admin Actions */
	define( 'WPVR_ENABLE_SETTERS', true );
	/* Enable cleaning the duplicates thumbnails on merging ? */
	define( 'WPVR_CLEAN_DUPS_THUMBS', false );
	
	/* Enable/Disable Use minified css assets */
	define( 'WPVR_USE_MIN_CSS', true );
	define( 'WPVR_USE_LOCAL_FONTAWESOME', false );
	
	/* Enable/Disable Use minified js assets */
	define( 'WPVR_USE_MIN_JS', true );
	
	/*Enable data Fillers to adapt to populate custom fields with video data*/
	define( 'WPVR_ENABLE_DATA_FILLERS', true );
	
	/* Enableor Disable Wordpress Post Formats */
	define( 'WPVR_ENABLE_POST_FORMATS', true );
	
	/* Enable this to get full video description */
	define( 'WPVR_FULL_DESC', false );
	
	
	/* COMPONENTS */
	/*************************************************/
	/* FRONT END AUTO CUSTOMIZATIONS  */
	
	/* Prevent from showing featured image on single video */
	define( 'WPVR_REMOVE_THUMB_SINGLE', false );
	
	/* Prevent from showing content on archive loop */
	define( 'WPVR_REMOVE_FLOW_CONTENT', false );
	
	/* Prevent from showing tags on archive loop */
	define( 'WPVR_REMOVE_FLOW_TAGS', false );
	
	/* EGFIX */
	define( 'WPVR_EG_FIX', false );
	
	/* Smooth Screens */
	define( 'WPVR_SMOOTH_SCREEN_ENABLED', false );
	
	/* FRONT AUTO CUSTOMIZATIONS  */
	/*************************************************/
	/* TEChNICAL OPTIONS  */
	
	/* Enable Hierarchy in Posting Category Select ? */
	define( 'WPVR_HIERARCHICAL_CATS_ENABLED', true );
	
	/* Buffer on Bulk Import Videos */
	define( 'WPVR_BULK_IMPORT_BUFFER', 2 );
	
	/* Define whether to enable or no the batch adding videos button */
	define( 'WPVR_BATCH_ADDING_ENABLED', false );
	
	/* Increase PHP Max Execution Time to improve performances [in seconds] */
	define( 'WPVR_MAX_EXECUTION_TIME', 600 );
	
	/* Force connection to APIS with credentials */
	define( 'WPVR_FORCE_CREDENTIALS_API_CONNECT', false );
	
	/* Enable/Disable Showing Demo NOtice Message */
	define( 'WPVR_IS_DEMO', false );
	
	/* Defining non admin Users capabilities */
	/**********************************************************************************/
	/* Non Admin users can manage options ? */
	define( 'WPVR_NONADMIN_CAP_OPTIONS', true );
	
	/* Non Admin users can show logs */
	define( 'WPVR_NONADMIN_CAP_LOG', true );
	
	/* Non Admin users can import sources/videos */
	define( 'WPVR_NONADMIN_CAP_IMPORT', true );
	
	/* Non Admin users can run actions (testing, running, etc ...) */
	define( 'WPVR_NONADMIN_CAP_ACTIONS', true );
	
	/* Non Admin users can manage imported videos ?*/
	define( 'WPVR_NONADMIN_CAP_MANAGE', true );
	
	/* Non Admin users can manage deferred videos ?*/
	define( 'WPVR_NONADMIN_CAP_DEFERRED', true );
	/**********************************************************************************/
	
	/* Enable Admin BAr Menu ? */
	define( 'WPVR_ENABLE_ADMINBAR_MENU', true );
	
	/* Defining non admin Users capabilities */
	/**********************************************************************************/
	
	/* Enable debug Mode */
	define( 'WPVR_DEV_MODE', false );
	
	/* Force to USe Async ACtions URL */
	define( 'WPVR_ACTIONS_URL_ASYNC_FIX', true );
	
	/**********************************************************************************/
	
	/* Change AUTH LIST NAME */
	define( 'WPVR_AUTH_CUSTOM_LIST', 'WPVR_USERS_' . WPVR_VERSION );
	
	/* TEChNICAL OPTIONS  */
	/***********************************************/

